theme: jekyll-theme-cayman

# Site Settings
locale                   : "Montréal, Canada"
title                    : "Norma Forero."
title_separator          : "-"
name                     : &name "Norma Forero "
description              : &description "Disease ecology"

# Social Sharing
twitter:
  username               : &twitter "norma_forero"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

