theme: jekyll-theme-cayman

# Site Settings
locale                   : "Montréal, Canada"
title                    : "Norma Forero."
title_separator          : "-"
name                     : &name "Norma Forero "
description              : &description "Norma Rocio Forero Muñoz, E. Acheson, F. Viard, P. Leighton, T. Poisot"
url                      : https://norma-forero.github.io/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "Norma-Foreroo/norma-forero.github.io"
# Social Sharing
twitter:
  username               : &twitter "norma_forero"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

